FROM ros:noetic-ros-core

RUN apt-get update \
    && apt-get install -y build-essential python3-rosdep curl \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Download + unpack basler-tof-driver library
RUN curl -SL https://www.baslerweb.com/fp-1528894787/media/downloads/software/tof_software/basler-tof-driver-1.4.1.1450-x86_64.tar.gz \
        | tar -xz --strip-components=1 -C /opt BaslerToF-1.4.1.1450/BaslerToF

# Patch library to avoid "error: cannot bind non-const lvalue reference of type ‘const void*&’ to an rvalue of type ‘const void*’"
COPY patch/BaslerToF-1.4.1-fix-non-const-lvalue-reference-cxx14.patch /tmp
RUN patch -p1 < /tmp/BaslerToF-1.4.1-fix-non-const-lvalue-reference-cxx14.patch && rm /tmp/BaslerToF-1.4.1-fix-non-const-lvalue-reference-cxx14.patch

# workaround for https://github.com/catkin/catkin_tools/issues/594:
# apt-get install python3-catkin-tools doesn't work because python3-trollius doesn't exist on Ubuntu Focal

ENV PATH="/root/.local/bin:${PATH}"

RUN apt-get update \
    && apt-get install -y git python3-pip \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN pip3 install --user git+https://github.com/catkin/catkin_tools.git

# end workaround

# Create ROS workspace
COPY . /ws/src/basler_tof
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep init && rosdep update && DEBIAN_FRONTEND=noninteractive rosdep install --from-paths src -i -y --rosdistro noetic

RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin build --limit-status-rate 0.1 --no-notify && \
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
