FROM ros:melodic-ros-core

RUN apt-get update && apt-get install -y \
    build-essential python-catkin-tools curl

# Download + unpack basler-tof-driver library
RUN curl -SL https://www.baslerweb.com/fp-1528894787/media/downloads/software/tof_software/basler-tof-driver-1.4.1.1450-x86_64.tar.gz \
        | tar -xz --strip-components=1 -C /opt BaslerToF-1.4.1.1450/BaslerToF

# Create ROS workspace
COPY . /ws/src/basler_tof
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep install --from-paths src -i -y --rosdistro melodic

RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin build --limit-status-rate 0.1 --no-notify && \
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
